---
layout: page
title: 자연어 처리 - 텍스트
subtitle: "워드 임베딩(Word Embedding): 한국어"
author:
  name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
  url: https://www.facebook.com/groups/tidyverse/
  affiliation: Tidyverse Korea
  affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: no
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(pdftools)
library(tidyverse)
library(magick)

```


# 왜 워드 임베딩인가? [^why-word-embedding] {#why-word-embedding}

[^why-word-embedding]: [Natasha Latysheva (Sep 10, 2019), "Why do we use word embeddings in NLP?", Towards Data Science](https://towardsdatascience.com/why-do-we-use-embeddings-in-nlp-2f20e1b632d2)

# 


```{r word-embedding-king}
library(tidyverse)
library(textdata)

glove6b <- embedding_glove6b(dimensions = 100)

glove6b
```

