---
layout: page
title: 자연어 처리 - 텍스트
subtitle: "기계독해(MRC): `RBERT`"
author:
  name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
  url: https://www.facebook.com/groups/tidyverse/
  affiliation: Tidyverse Korea
  affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(pdftools)
library(tidyverse)
library(magick)

```


# 의존성 문제 해결 [^figure-out-keras] {#figure-out-dependencies}

[^figure-out-keras]: [Dr. Bharatendra Rai (2020. 7. 12.), "Installing the Latest Tensorflow, Keras & Python for R & RStudio"](https://www.youtube.com/watch?v=-IYYqdxdYXk)

[`RBERT`](https://github.com/jonathanbratt/RBERT)를 실행시키기 위해서 `tensorflow`가 필요한데 이에 대한 선행 작업을 다음과 같이 수행한다.

- 파이썬 3 설치
    - `brew install python3`

```{bash check python-version}
python --version
```

- `virtualenv` 설치
    - `brew install virtualenv`

```{bash check-virtualenv-version, eval = FALSE}
virtualenv --version
```

## `reticulate` 설정

```{r}
reticulate::py_config()
```

```{r set-environment, eval = FALSE}
Sys.setenv(RETICULATE_PYTHON = "/Users/kwangchunlee/Library/r-miniconda/envs/r-reticulate/bin/python")
```


```{r}
library(tensorflow)
library(keras)

tf$constant("Hellow Tensorflow")
```

# [`RBERT`](https://github.com/jonathanbratt/RBERT) 설치 {#install-rbert}

```{r rbert-install}
# tensorflow::install_tensorflow(version = "1.13.1")
# devtools::install_github("jonathanbratt/RBERT", build_vignettes = TRUE)

library(RBERT)
library(tidyverse)

BERT_PRETRAINED_DIR <- RBERT::download_BERT_checkpoint(
  model = "bert_base_uncased"
)

text_to_process <- c("Impulse is equal to the change in momentum.",
                     "Changing momentum requires an impulse.",
                     "An impulse is like a push.",
                     "Impulse is force times time.")

BERT_feats <- extract_features(
  examples = text_to_process,
  ckpt_dir = BERT_PRETRAINED_DIR
)

BERT_feats

output_vector1 <- BERT_feats$output %>%
  dplyr::filter(
    sequence_index == 1, 
    token == "[CLS]", 
    layer_index == 12
  ) %>% 
  dplyr::select(dplyr::starts_with("V")) %>% 
  unlist()
output_vector1

```

```{r}
tokens <- tokenize_text(text = "Who doesn't like tacos?",
                        ckpt_dir = BERT_PRETRAINED_DIR)
tokens
```

```{r}
check_vocab(words = c("positron", "electron"), ckpt_dir = BERT_PRETRAINED_DIR)
```

