---
layout: page
title: 자연어 처리 - 텍스트
subtitle: "최고의 OCR 엔진: 구글, 네이버, Azure, `tesseract`"
author:
  - name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
    affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(pdftools)
library(tidyverse)
library(magick)
```


# OCR 엔진 {#extract-text-ocr-engine}

OCR 엔진은 오픈소스 [`tesseract`](https://github.com/tesseract-ocr)를 비롯하여 구글, 네이버, Azure가 한국어 OCR 인식에서 강점을 보이고 있다.

## `tesseract` 오픈 소스 {#tesseract-open-source}

먼저 `tesseract` 오픈 소스 팩키지를 활용하여 한국어 인식을 한다. 70 페이지로 다소 공청회 자료집이 두꺼운 관계로 `278`초 대략 4~5분 정도 소요된다.

```{r ocr-tesseract-engine, eval = FALSE}
library(tesseract)
library(tictoc)

fair_pdf <- image_read_pdf("data/fair_hearing.pdf")

if(is.na(match("kor", tesseract_info()$available)))
  tesseract_download("kor")

tic()
fair_text <- tesseract::ocr(fair_pdf, engine = tesseract(language = "kor"))  
toc()
# 278.035 sec elapsed

dir.create("data/ocred", showWarnings = FALSE)

fair_text %>% 
  write_rds("data/ocred/fair_tesseract.rds")
```

## Azure API {#azure-api}

```{r azure-api}

```

